### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Counterfeiter** [petosa/multiplayer-alphazero#2]
Hello,

I would like to send pull requests and did not see any license file. Could you please add one?

I have added a hidden states variable (e.g. a complete gym env) to the game class. The hash function is also redirected to the game interface, so this could handle games with incomplete information.

I think thats a great improvement to support a lot more games and should gain more interest. This repo is really underestimated compared to other alpha zero implementations.

Thanks

Sebastian

**Comment by petosa** [comment]
Hi Sebastian, please do.

**Comment by petosa** [comment]
I will add the license.

**Comment by Counterfeiter** [comment]
thx!
